test:
  clients:
    default:
      database: <%= ENV['DBNAME'] || 'alive_test' %>
      hosts:
        - localhost:27017
      options:
        max_pool_size: 1

development:
  clients:
    default:
      database: <%= ENV['DBNAME'] || 'alive_development' %>
      hosts:
        - localhost:27017
      options:
        max_pool_size: 2

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URL'] %>
      options:
        min_pool_size: 5
        max_pool_size: 200
